spring:
  application:
    name: K8s-Health-Probes
  datasource:
    username: k8s-user
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    username: k8s-user
    password: password
  redis:
    host: localhost

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "readinessState,db,rabbit,redis"
